global:
  resolve_timeout: 5m

route:
 group_by: ['...']
 # If an alert isn't caught by a route, send it slack.
 receiver: slack_general

receivers:
- name: slack_general
  slack_configs:
  - api_url: https://hooks.slack.com/services/<VOTRE WEBHOOK SLACK>   
    channel: alert-prod                                               
    icon_emoji: ":rotating_light:"                                    
    title_link: "http://127.0.0.1:9090/alerts"                        
    send_resolved: true                                               
    title: '{{ template "custom_title" . }}'                          
    text: '{{ template "custom_slack_message" . }}'                   

templates:
  - '/etc/alertmanager/templates/default.tmpl' 
