global:
  scrape_interval:     15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    env: 'infrastructure'

# alertmanager

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
    scheme: http
    timeout: 10s

rule_files:
  - "/alertmanager/alert.rules/alerts.rules.yml"

scrape_configs:

  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']
    scrape_interval: 5s

#  - job_name: 'cadvisor-exporter'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['cadvisor-exporter:8080']

