groups:
 
- name: Alertes monitoring
  rules:
    - alert: OutOfMemory
      expr: (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes * 100 < 10
      for: 10s
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "Out of memory (instance {{ $labels.instance }})"
        description: "<!channel>  RAM (< 10% restant)    VALUE = {{ $value }}    LABELS: {{ $labels.job }} : {{ $labels.instance }}"

    - alert: CpuLoad
      expr: node_load15 / (count without (cpu, mode) (node_cpu_seconds_total{mode="system"})) > 2
      for: 10s
      labels:
        severity: critique
      annotations:
        identifier: "{{ $labels.instance }}"
        summary: "CPU load (instance {{ $labels.instance }})"
        description: "<!channel>  CPU (10s) high   VALUE = {{ $value }}    LABELS: {{ $labels.job }} : {{ $labels.instance }}"

